name: Client CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dep
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: "npm"
          cache-dependency-path: client/package-lock.json
  
  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run e2e
        run: npm run e2e-test